
// user define
#define DWL_FALSE 											  	 0
#define DWL_TRUE 												 1
#define DWL_INFO_LOG_LENGTH                						 0x8B84

// https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Constants
#define DWL_DEPTH_BUFFER_BIT                                     0x0100
#define DWL_STENCIL_BUFFER_BIT                                   0x0400
#define DWL_COLOR_BUFFER_BIT                                     0x4000
#define DWL_POINTS                                               0x0000
#define DWL_LINES                                                0x0001
#define DWL_LINE_LOOP                                            0x0002
#define DWL_LINE_STRIP                                           0x0003
#define DWL_TRIANGLES                                            0x0004
#define DWL_TRIANGLE_STRIP                                       0x0005
#define DWL_TRIANGLE_FAN                                         0x0006
#define DWL_ZERO                                                 0
#define DWL_ONE                                                  1
#define DWL_SRC_COLOR                                            0x0300
#define DWL_ONE_MINUS_SRC_COLOR                                  0x0301
#define DWL_SRC_ALPHA                                            0x0302
#define DWL_ONE_MINUS_SRC_ALPHA                                  0x0303
#define DWL_DST_ALPHA                                            0x0304
#define DWL_ONE_MINUS_DST_ALPHA                                  0x0305
#define DWL_DST_COLOR                                            0x0306
#define DWL_ONE_MINUS_DST_COLOR                                  0x0307
#define DWL_SRC_ALPHA_SATURATE                                   0x0308
#define DWL_CONSTANT_COLOR                                       0x8001
#define DWL_ONE_MINUS_CONSTANT_COLOR                             0x8002
#define DWL_CONSTANT_ALPHA                                       0x8003
#define DWL_ONE_MINUS_CONSTANT_ALPHA                             0x8004
#define DWL_FUNC_ADD                                             0x8006
#define DWL_FUNC_SUBTRACT                                        0x800A
#define DWL_FUNC_REVERSE_SUBTRACT                                0x800B
#define DWL_BLEND_EQUATION                                       0x8009
#define DWL_BLEND_EQUATION_RGB                                   0x8009
#define DWL_BLEND_EQUATION_ALPHA                                 0x883D
#define DWL_BLEND_DST_RGB                                        0x80C8
#define DWL_BLEND_SRC_RGB                                        0x80C9
#define DWL_BLEND_DST_ALPHA                                      0x80CA
#define DWL_BLEND_SRC_ALPHA                                      0x80CB
#define DWL_BLEND_COLOR                                          0x8005
#define DWL_ARRAY_BUFFER_BINDING                                 0x8894
#define DWL_ELEMENT_ARRAY_BUFFER_BINDING                         0x8895
#define DWL_LINE_WIDTH                                           0x0B21
#define DWL_ALIASED_POINT_SIZE_RANGE                             0x846D
#define DWL_ALIASED_LINE_WIDTH_RANGE                             0x846E
#define DWL_CULL_FACE_MODE                                       0x0B45
#define DWL_FRONT_FACE                                           0x0B46
#define DWL_DEPTH_RANGE                                          0x0B70
#define DWL_DEPTH_WRITEMASK                                      0x0B72
#define DWL_DEPTH_CLEAR_VALUE                                    0x0B73
#define DWL_DEPTH_FUNC                                           0x0B74
#define DWL_STENCIL_CLEAR_VALUE                                  0x0B91
#define DWL_STENCIL_FUNC                                         0x0B92
#define DWL_STENCIL_FAIL                                         0x0B94
#define DWL_STENCIL_PASS_DEPTH_FAIL                              0x0B95
#define DWL_STENCIL_PASS_DEPTH_PASS                              0x0B96
#define DWL_STENCIL_REF                                          0x0B97
#define DWL_STENCIL_VALUE_MASK                                   0x0B93
#define DWL_STENCIL_WRITEMASK                                    0x0B98
#define DWL_STENCIL_BACK_FUNC                                    0x8800
#define DWL_STENCIL_BACK_FAIL                                    0x8801
#define DWL_STENCIL_BACK_PASS_DEPTH_FAIL                         0x8802
#define DWL_STENCIL_BACK_PASS_DEPTH_PASS                         0x8803
#define DWL_STENCIL_BACK_REF                                     0x8CA3
#define DWL_STENCIL_BACK_VALUE_MASK                              0x8CA4
#define DWL_STENCIL_BACK_WRITEMASK                               0x8CA5
#define DWL_VIEWPORT                                             0x0BA2
#define DWL_SCISSOR_BOX                                          0x0C10
#define DWL_COLOR_CLEAR_VALUE                                    0x0C22
#define DWL_COLOR_WRITEMASK                                      0x0C23
#define DWL_UNPACK_ALIGNMENT                                     0x0CF5
#define DWL_PACK_ALIGNMENT                                       0x0D05
#define DWL_MAX_TEXTURE_SIZE                                     0x0D33
#define DWL_MAX_VIEWPORT_DIMS                                    0x0D3A
#define DWL_SUBPIXEL_BITS                                        0x0D50
#define DWL_RED_BITS                                             0x0D52
#define DWL_GREEN_BITS                                           0x0D53
#define DWL_BLUE_BITS                                            0x0D54
#define DWL_ALPHA_BITS                                           0x0D55
#define DWL_DEPTH_BITS                                           0x0D56
#define DWL_STENCIL_BITS                                         0x0D57
#define DWL_POLYGON_OFFSET_UNITS                                 0x2A00
#define DWL_POLYGON_OFFSET_FACTOR                                0x8038
#define DWL_TEXTURE_BINDING_2D                                   0x8069
#define DWL_SAMPLE_BUFFERS                                       0x80A8
#define DWL_SAMPLES                                              0x80A9
#define DWL_SAMPLE_COVERAGE_VALUE                                0x80AA
#define DWL_SAMPLE_COVERAGE_INVERT                               0x80AB
#define DWL_COMPRESSED_TEXTURE_FORMATS                           0x86A3
#define DWL_VENDOR                                               0x1F00
#define DWL_RENDERER                                             0x1F01
#define DWL_VERSION                                              0x1F02
#define DWL_IMPLEMENTATION_COLOR_READ_TYPE                       0x8B9A
#define DWL_IMPLEMENTATION_COLOR_READ_FORMAT                     0x8B9B
#define DWL_BROWSER_DEFAULT_WEBGL                                0x9244
#define DWL_STATIC_DRAW                                          0x88E4
#define DWL_STREAM_DRAW                                          0x88E0
#define DWL_DYNAMIC_DRAW                                         0x88E8
#define DWL_ARRAY_BUFFER                                         0x8892
#define DWL_ELEMENT_ARRAY_BUFFER                                 0x8893
#define DWL_BUFFER_SIZE                                          0x8764
#define DWL_BUFFER_USAGE                                         0x8765
#define DWL_CURRENT_VERTEX_ATTRIB                                0x8626
#define DWL_VERTEX_ATTRIB_ARRAY_ENABLED                          0x8622
#define DWL_VERTEX_ATTRIB_ARRAY_SIZE                             0x8623
#define DWL_VERTEX_ATTRIB_ARRAY_STRIDE                           0x8624
#define DWL_VERTEX_ATTRIB_ARRAY_TYPE                             0x8625
#define DWL_VERTEX_ATTRIB_ARRAY_NORMALIZED                       0x886A
#define DWL_VERTEX_ATTRIB_ARRAY_POINTER                          0x8645
#define DWL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING                   0x889F
#define DWL_CULL_FACE                                            0x0B44
#define DWL_FRONT                                                0x0404
#define DWL_BACK                                                 0x0405
#define DWL_FRONT_AND_BACK                                       0x0408
#define DWL_BLEND                                                0x0BE2
#define DWL_DEPTH_TEST                                           0x0B71
#define DWL_DITHER                                               0x0BD0
#define DWL_POLYGON_OFFSET_FILL                                  0x8037
#define DWL_SAMPLE_ALPHA_TO_COVERAGE                             0x809E
#define DWL_SAMPLE_COVERAGE                                      0x80A0
#define DWL_SCISSOR_TEST                                         0x0C11
#define DWL_STENCIL_TEST                                         0x0B90
#define DWL_NO_ERROR                                             0
#define DWL_INVALID_ENUM                                         0x0500
#define DWL_INVALID_VALUE                                        0x0501
#define DWL_INVALID_OPERATION                                    0x0502
#define DWL_OUT_OF_MEMORY                                        0x0505
#define DWL_CONTEXT_LOST_WEBGL                                   0x9242
#define DWL_CW                                                   0x0900
#define DWL_CCW                                                  0x0901
#define DWL_DONT_CARE                                            0x1100
#define DWL_FASTEST                                              0x1101
#define DWL_NICEST                                               0x1102
#define DWL_GENERATE_MIPMAP_HINT                                 0x8192
#define DWL_BYTE                                                 0x1400
#define DWL_UNSIGNED_BYTE                                        0x1401
#define DWL_SHORT                                                0x1402
#define DWL_UNSIGNED_SHORT                                       0x1403
#define DWL_INT                                                  0x1404
#define DWL_UNSIGNED_INT                                         0x1405
#define DWL_FLOAT                                                0x1406
#define DWL_DEPTH_COMPONENT                                      0x1902
#define DWL_ALPHA                                                0x1906
#define DWL_RGB                                                  0x1907
#define DWL_RGBA                                                 0x1908
#define DWL_LUMINANCE                                            0x1909
#define DWL_LUMINANCE_ALPHA                                      0x190A
#define DWL_UNSIGNED_SHORT_4_4_4_4                               0x8033
#define DWL_UNSIGNED_SHORT_5_5_5_1                               0x8034
#define DWL_UNSIGNED_SHORT_5_6_5                                 0x8363
#define DWL_FRAGMENT_SHADER                                      0x8B30
#define DWL_VERTEX_SHADER                                        0x8B31
#define DWL_COMPILE_STATUS                                       0x8B81
#define DWL_DELETE_STATUS                                        0x8B80
#define DWL_LINK_STATUS                                          0x8B82
#define DWL_VALIDATE_STATUS                                      0x8B83
#define DWL_ATTACHED_SHADERS                                     0x8B85
#define DWL_ACTIVE_ATTRIBUTES                                    0x8B89
#define DWL_ACTIVE_UNIFORMS                                      0x8B86
#define DWL_MAX_VERTEX_ATTRIBS                                   0x8869
#define DWL_MAX_VERTEX_UNIFORM_VECTORS                           0x8DFB
#define DWL_MAX_VARYING_VECTORS                                  0x8DFC
#define DWL_MAX_COMBINED_TEXTURE_IMAGE_UNITS                     0x8B4D
#define DWL_MAX_VERTEX_TEXTURE_IMAGE_UNITS                       0x8B4C
#define DWL_MAX_TEXTURE_IMAGE_UNITS                              0x8872
#define DWL_MAX_FRAGMENT_UNIFORM_VECTORS                         0x8DFD
#define DWL_SHADER_TYPE                                          0x8B4F
#define DWL_SHADING_LANGUAGE_VERSION                             0x8B8C
#define DWL_CURRENT_PROGRAM                                      0x8B8D
#define DWL_NEVER                                                0x0200
#define DWL_ALWAYS                                               0x0207
#define DWL_LESS                                                 0x0201
#define DWL_EQUAL                                                0x0202
#define DWL_LEQUAL                                               0x0203
#define DWL_GREATER                                              0x0204
#define DWL_GEQUAL                                               0x0206
#define DWL_NOTEQUAL                                             0x0205
#define DWL_KEEP                                                 0x1E00
#define DWL_REPLACE                                              0x1E01
#define DWL_INCR                                                 0x1E02
#define DWL_DECR                                                 0x1E03
#define DWL_INVERT                                               0x150A
#define DWL_INCR_WRAP                                            0x8507
#define DWL_DECR_WRAP                                            0x8508
#define DWL_NEAREST                                              0x2600
#define DWL_LINEAR                                               0x2601
#define DWL_NEAREST_MIPMAP_NEAREST                               0x2700
#define DWL_LINEAR_MIPMAP_NEAREST                                0x2701
#define DWL_NEAREST_MIPMAP_LINEAR                                0x2702
#define DWL_LINEAR_MIPMAP_LINEAR                                 0x2703
#define DWL_TEXTURE_MAG_FILTER                                   0x2800
#define DWL_TEXTURE_MIN_FILTER                                   0x2801
#define DWL_TEXTURE_WRAP_S                                       0x2802
#define DWL_TEXTURE_WRAP_T                                       0x2803
#define DWL_TEXTURE_2D                                           0x0DE1
#define DWL_TEXTURE                                              0x1702
#define DWL_TEXTURE_CUBE_MAP                                     0x8513
#define DWL_TEXTURE_BINDING_CUBE_MAP                             0x8514
#define DWL_TEXTURE_CUBE_MAP_POSITIVE_X                          0x8515
#define DWL_TEXTURE_CUBE_MAP_NEGATIVE_X                          0x8516
#define DWL_TEXTURE_CUBE_MAP_POSITIVE_Y                          0x8517
#define DWL_TEXTURE_CUBE_MAP_NEGATIVE_Y                          0x8518
#define DWL_TEXTURE_CUBE_MAP_POSITIVE_Z                          0x8519
#define DWL_TEXTURE_CUBE_MAP_NEGATIVE_Z                          0x851A
#define DWL_MAX_CUBE_MAP_TEXTURE_SIZE                            0x851C
#define DWL_TEXTURE0                                             0x84C0
#define DWL_TEXTURE1                                             0x84C1
#define DWL_TEXTURE2                                      	   	 0x84C2
#define DWL_TEXTURE3                                      	     0x84C3
#define DWL_TEXTURE4                                      	     0x84C4
#define DWL_TEXTURE5                                      	     0x84C5
#define DWL_TEXTURE6                                      	     0x84C6
#define DWL_TEXTURE7                                      	     0x84C7
#define DWL_TEXTURE8                                      	     0x84C8
#define DWL_TEXTURE9                                      	     0x84C9
#define DWL_TEXTURE10                                     	     0x84CA
#define DWL_TEXTURE11                                     	     0x84CB
#define DWL_TEXTURE12                                     	     0x84CC
#define DWL_TEXTURE13                                     	     0x84CD
#define DWL_TEXTURE14                                     	     0x84CE
#define DWL_TEXTURE15                                     	     0x84CF
#define DWL_TEXTURE16                                     	     0x84D0
#define DWL_TEXTURE17                                     	     0x84D1
#define DWL_TEXTURE18                                     	     0x84D2
#define DWL_TEXTURE19                                     	     0x84D3
#define DWL_TEXTURE20                                     	     0x84D4
#define DWL_TEXTURE21                                     	     0x84D5
#define DWL_TEXTURE22                                     	     0x84D6
#define DWL_TEXTURE23                                     	     0x84D7
#define DWL_TEXTURE24                                     	     0x84D8
#define DWL_TEXTURE25                                     	     0x84D9
#define DWL_TEXTURE26                                     	     0x84DA
#define DWL_TEXTURE27                                     	     0x84DB
#define DWL_TEXTURE28                                     	     0x84DC
#define DWL_TEXTURE29                                     	     0x84DD
#define DWL_TEXTURE30                                     	     0x84DE
#define DWL_TEXTURE31                                     	     0x84CF
#define DWL_ACTIVE_TEXTURE                                       0x84E0
#define DWL_REPEAT                                               0x2901
#define DWL_CLAMP_TO_EDGE                                        0x812F
#define DWL_MIRRORED_REPEAT                                      0x8370
#define DWL_FLOAT_VEC2                                           0x8B50
#define DWL_FLOAT_VEC3                                           0x8B51
#define DWL_FLOAT_VEC4                                           0x8B52
#define DWL_INT_VEC2                                             0x8B53
#define DWL_INT_VEC3                                             0x8B54
#define DWL_INT_VEC4                                             0x8B55
#define DWL_BOOL                                                 0x8B56
#define DWL_BOOL_VEC2                                            0x8B57
#define DWL_BOOL_VEC3                                            0x8B58
#define DWL_BOOL_VEC4                                            0x8B59
#define DWL_FLOAT_MAT2                                           0x8B5A
#define DWL_FLOAT_MAT3                                           0x8B5B
#define DWL_FLOAT_MAT4                                           0x8B5C
#define DWL_SAMPLER_2D                                           0x8B5E
#define DWL_SAMPLER_CUBE                                         0x8B60
#define DWL_LOW_FLOAT                                            0x8DF0
#define DWL_MEDIUM_FLOAT                                         0x8DF1
#define DWL_HIGH_FLOAT                                           0x8DF2
#define DWL_LOW_INT                                              0x8DF3
#define DWL_MEDIUM_INT                                           0x8DF4
#define DWL_HIGH_INT                                             0x8DF5
#define DWL_FRAMEBUFFER                                          0x8D40
#define DWL_RENDERBUFFER                                         0x8D41
#define DWL_RGBA4                                                0x8056
#define DWL_RGB5_A1                                              0x8057
#define DWL_RGB565                                               0x8D62
#define DWL_DEPTH_COMPONENT16                                    0x81A5
#define DWL_STENCIL_INDEX                                        0x1901
#define DWL_STENCIL_INDEX8                                       0x8D48
#define DWL_DEPTH_STENCIL                                        0x84F9
#define DWL_RENDERBUFFER_WIDTH                                   0x8D42
#define DWL_RENDERBUFFER_HEIGHT                                  0x8D43
#define DWL_RENDERBUFFER_INTERNAL_FORMAT                         0x8D44
#define DWL_RENDERBUFFER_RED_SIZE                                0x8D50
#define DWL_RENDERBUFFER_GREEN_SIZE                              0x8D51
#define DWL_RENDERBUFFER_BLUE_SIZE                               0x8D52
#define DWL_RENDERBUFFER_ALPHA_SIZE                              0x8D53
#define DWL_RENDERBUFFER_DEPTH_SIZE                              0x8D54
#define DWL_RENDERBUFFER_STENCIL_SIZE                            0x8D55
#define DWL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE                   0x8CD0
#define DWL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME                   0x8CD1
#define DWL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL                 0x8CD2
#define DWL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE         0x8CD3
#define DWL_COLOR_ATTACHMENT0                                    0x8CE0
#define DWL_DEPTH_ATTACHMENT                                     0x8D00
#define DWL_STENCIL_ATTACHMENT                                   0x8D20
#define DWL_DEPTH_STENCIL_ATTACHMENT                             0x821A
#define DWL_NONE                                                 0
#define DWL_FRAMEBUFFER_COMPLETE                                 0x8CD5
#define DWL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT                    0x8CD6
#define DWL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT            0x8CD7
#define DWL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS                    0x8CD9
#define DWL_FRAMEBUFFER_UNSUPPORTED                              0x8CDD
#define DWL_FRAMEBUFFER_BINDING                                  0x8CA6
#define DWL_RENDERBUFFER_BINDING                                 0x8CA7
#define DWL_MAX_RENDERBUFFER_SIZE                                0x84E8
#define DWL_INVALID_FRAMEBUFFER_OPERATION                        0x0506
#define DWL_UNPACK_FLIP_Y_WEBGL                                  0x9240
#define DWL_UNPACK_PREMULTIPLY_ALPHA_WEBGL                       0x9241
#define DWL_UNPACK_COLORSPACE_CONVERSION_WEBGL                   0x9243
#define DWL_READ_BUFFER                                          0x0C02
#define DWL_UNPACK_ROW_LENGTH                                    0x0CF2
#define DWL_UNPACK_SKIP_ROWS                                     0x0CF3
#define DWL_UNPACK_SKIP_PIXELS                                   0x0CF4
#define DWL_PACK_ROW_LENGTH                                      0x0D02
#define DWL_PACK_SKIP_ROWS                                       0x0D03
#define DWL_PACK_SKIP_PIXELS                                     0x0D04
#define DWL_TEXTURE_BINDING_3D                                   0x806A
#define DWL_UNPACK_SKIP_IMAGES                                   0x806D
#define DWL_UNPACK_IMAGE_HEIGHT                                  0x806E
#define DWL_MAX_3D_TEXTURE_SIZE                                  0x8073
#define DWL_MAX_ELEMENTS_VERTICES                                0x80E8
#define DWL_MAX_ELEMENTS_INDICES                                 0x80E9
#define DWL_MAX_TEXTURE_LOD_BIAS                                 0x84FD
#define DWL_MAX_FRAGMENT_UNIFORM_COMPONENTS                      0x8B49
#define DWL_MAX_VERTEX_UNIFORM_COMPONENTS                        0x8B4A
#define DWL_MAX_ARRAY_TEXTURE_LAYERS                             0x88FF
#define DWL_MIN_PROGRAM_TEXEL_OFFSET                             0x8904
#define DWL_MAX_PROGRAM_TEXEL_OFFSET                             0x8905
#define DWL_MAX_VARYING_COMPONENTS                               0x8B4B
#define DWL_FRAGMENT_SHADER_DERIVATIVE_HINT                      0x8B8B
#define DWL_RASTERIZER_DISCARD                                   0x8C89
#define DWL_VERTEX_ARRAY_BINDING                                 0x85B5
#define DWL_MAX_VERTEX_OUTPUT_COMPONENTS                         0x9122
#define DWL_MAX_FRAGMENT_INPUT_COMPONENTS                        0x9125
#define DWL_MAX_SERVER_WAIT_TIMEOUT                              0x9111
#define DWL_MAX_ELEMENT_INDEX                                    0x8D6B
#define DWL_RED                                                  0x1903
#define DWL_RGB8                                                 0x8051
#define DWL_RGBA8                                                0x8058
#define DWL_RGB10_A2                                             0x8059
#define DWL_TEXTURE_3D                                           0x806F
#define DWL_TEXTURE_WRAP_R                                       0x8072
#define DWL_TEXTURE_MIN_LOD                                      0x813A
#define DWL_TEXTURE_MAX_LOD                                      0x813B
#define DWL_TEXTURE_BASE_LEVEL                                   0x813C
#define DWL_TEXTURE_MAX_LEVEL                                    0x813D
#define DWL_TEXTURE_COMPARE_MODE                                 0x884C
#define DWL_TEXTURE_COMPARE_FUNC                                 0x884D
#define DWL_SRGB                                                 0x8C40
#define DWL_SRGB8                                                0x8C41
#define DWL_SRGB8_ALPHA8                                         0x8C43
#define DWL_COMPARE_REF_TO_TEXTURE                               0x884E
#define DWL_RGBA32F                                              0x8814
#define DWL_RGB32F                                               0x8815
#define DWL_RGBA16F                                              0x881A
#define DWL_RGB16F                                               0x881B
#define DWL_TEXTURE_2D_ARRAY                                     0x8C1A
#define DWL_TEXTURE_BINDING_2D_ARRAY                             0x8C1D
#define DWL_R11F_G11F_B10F                                       0x8C3A
#define DWL_RGB9_E5                                              0x8C3D
#define DWL_RGBA32UI                                             0x8D70
#define DWL_RGB32UI                                              0x8D71
#define DWL_RGBA16UI                                             0x8D76
#define DWL_RGB16UI                                              0x8D77
#define DWL_RGBA8UI                                              0x8D7C
#define DWL_RGB8UI                                               0x8D7D
#define DWL_RGBA32I                                              0x8D82
#define DWL_RGB32I                                               0x8D83
#define DWL_RGBA16I                                              0x8D88
#define DWL_RGB16I                                               0x8D89
#define DWL_RGBA8I                                               0x8D8E
#define DWL_RGB8I                                                0x8D8F
#define DWL_RED_INTEGER                                          0x8D94
#define DWL_RGB_INTEGER                                          0x8D98
#define DWL_RGBA_INTEGER                                         0x8D99
#define DWL_R8                                                   0x8229
#define DWL_RG8                                                  0x822B
#define DWL_R16F                                                 0x822D
#define DWL_R32F                                                 0x822E
#define DWL_RG16F                                                0x822F
#define DWL_RG32F                                                0x8230
#define DWL_R8I                                                  0x8231
#define DWL_R8UI                                                 0x8232
#define DWL_R16I                                                 0x8233
#define DWL_R16UI                                                0x8234
#define DWL_R32I                                                 0x8235
#define DWL_R32UI                                                0x8236
#define DWL_RG8I                                                 0x8237
#define DWL_RG8UI                                                0x8238
#define DWL_RG16I                                                0x8239
#define DWL_RG16UI                                               0x823A
#define DWL_RG32I                                                0x823B
#define DWL_RG32UI                                               0x823C
#define DWL_R8_SNORM                                             0x8F94
#define DWL_RG8_SNORM                                            0x8F95
#define DWL_RGB8_SNORM                                           0x8F96
#define DWL_RGBA8_SNORM                                          0x8F97
#define DWL_RGB10_A2UI                                           0x906F
#define DWL_TEXTURE_IMMUTABLE_FORMAT                             0x912F
#define DWL_TEXTURE_IMMUTABLE_LEVELS                             0x82DF
#define DWL_UNSIGNED_INT_2_10_10_10_REV                          0x8368
#define DWL_UNSIGNED_INT_10F_11F_11F_REV                         0x8C3B
#define DWL_UNSIGNED_INT_5_9_9_9_REV                             0x8C3E
#define DWL_FLOAT_32_UNSIGNED_INT_24_8_REV                       0x8DAD
#define DWL_UNSIGNED_INT_24_8                                    0x84FA
#define DWL_HALF_FLOAT                                           0x140B
#define DWL_RG                                                   0x8227
#define DWL_RG_INTEGER                                           0x8228
#define DWL_INT_2_10_10_10_REV                                   0x8D9F
#define DWL_CURRENT_QUERY                                        0x8865
#define DWL_QUERY_RESULT                                         0x8866
#define DWL_QUERY_RESULT_AVAILABLE                               0x8867
#define DWL_ANY_SAMPLES_PASSED                                   0x8C2F
#define DWL_ANY_SAMPLES_PASSED_CONSERVATIVE                      0x8D6A
#define DWL_MAX_DRAW_BUFFERS                                     0x8824
#define DWL_DRAW_BUFFER0                                         0x8825
#define DWL_DRAW_BUFFER1                                         0x8826
#define DWL_DRAW_BUFFER2                                         0x8827
#define DWL_DRAW_BUFFER3                                         0x8828
#define DWL_DRAW_BUFFER4                                         0x8829
#define DWL_DRAW_BUFFER5                                         0x882A
#define DWL_DRAW_BUFFER6                                         0x882B
#define DWL_DRAW_BUFFER7                                         0x882C
#define DWL_DRAW_BUFFER8                                         0x882D
#define DWL_DRAW_BUFFER9                                         0x882E
#define DWL_DRAW_BUFFER10                                        0x882F
#define DWL_DRAW_BUFFER11                                        0x8830
#define DWL_DRAW_BUFFER12                                        0x8831
#define DWL_DRAW_BUFFER13                                        0x8832
#define DWL_DRAW_BUFFER14                                        0x8833
#define DWL_DRAW_BUFFER15                                        0x8834
#define DWL_MAX_COLOR_ATTACHMENTS                                0x8CDF
#define DWL_COLOR_ATTACHMENT1                                    0x8CE1
#define DWL_COLOR_ATTACHMENT2                                    0x8CE2
#define DWL_COLOR_ATTACHMENT3                                    0x8CE3
#define DWL_COLOR_ATTACHMENT4                                    0x8CE4
#define DWL_COLOR_ATTACHMENT5                                    0x8CE5
#define DWL_COLOR_ATTACHMENT6                                    0x8CE6
#define DWL_COLOR_ATTACHMENT7                                    0x8CE7
#define DWL_COLOR_ATTACHMENT8                                    0x8CE8
#define DWL_COLOR_ATTACHMENT9                                    0x8CE9
#define DWL_COLOR_ATTACHMENT10                                   0x8CEA
#define DWL_COLOR_ATTACHMENT11                                   0x8CEB
#define DWL_COLOR_ATTACHMENT12                                   0x8CEC
#define DWL_COLOR_ATTACHMENT13                                   0x8CED
#define DWL_COLOR_ATTACHMENT14                                   0x8CEE
#define DWL_COLOR_ATTACHMENT15                                   0x8CEF
#define DWL_SAMPLER_3D                                           0x8B5F
#define DWL_SAMPLER_2D_SHADOW                                    0x8B62
#define DWL_SAMPLER_2D_ARRAY                                     0x8DC1
#define DWL_SAMPLER_2D_ARRAY_SHADOW                              0x8DC4
#define DWL_SAMPLER_CUBE_SHADOW                                  0x8DC5
#define DWL_INT_SAMPLER_2D                                       0x8DCA
#define DWL_INT_SAMPLER_3D                                       0x8DCB
#define DWL_INT_SAMPLER_CUBE                                     0x8DCC
#define DWL_INT_SAMPLER_2D_ARRAY                                 0x8DCF
#define DWL_UNSIGNED_INT_SAMPLER_2D                              0x8DD2
#define DWL_UNSIGNED_INT_SAMPLER_3D                              0x8DD3
#define DWL_UNSIGNED_INT_SAMPLER_CUBE                            0x8DD4
#define DWL_UNSIGNED_INT_SAMPLER_2D_ARRAY                        0x8DD7
#define DWL_MAX_SAMPLES                                          0x8D57
#define DWL_SAMPLER_BINDING                                      0x8919
#define DWL_PIXEL_PACK_BUFFER                                    0x88EB
#define DWL_PIXEL_UNPACK_BUFFER                                  0x88EC
#define DWL_PIXEL_PACK_BUFFER_BINDING                            0x88ED
#define DWL_PIXEL_UNPACK_BUFFER_BINDING                          0x88EF
#define DWL_COPY_READ_BUFFER                                     0x8F36
#define DWL_COPY_WRITE_BUFFER                                    0x8F37
#define DWL_COPY_READ_BUFFER_BINDING                             0x8F36
#define DWL_COPY_WRITE_BUFFER_BINDING                            0x8F37
#define DWL_FLOAT_MAT2x3                                         0x8B65
#define DWL_FLOAT_MAT2x4                                         0x8B66
#define DWL_FLOAT_MAT3x2                                         0x8B67
#define DWL_FLOAT_MAT3x4                                         0x8B68
#define DWL_FLOAT_MAT4x2                                         0x8B69
#define DWL_FLOAT_MAT4x3                                         0x8B6A
#define DWL_UNSIGNED_INT_VEC2                                    0x8DC6
#define DWL_UNSIGNED_INT_VEC3                                    0x8DC7
#define DWL_UNSIGNED_INT_VEC4                                    0x8DC8
#define DWL_UNSIGNED_NORMALIZED                                  0x8C17
#define DWL_SIGNED_NORMALIZED                                    0x8F9C
#define DWL_VERTEX_ATTRIB_ARRAY_INTEGER                          0x88FD
#define DWL_VERTEX_ATTRIB_ARRAY_DIVISOR                          0x88FE
#define DWL_TRANSFORM_FEEDBACK_BUFFER_MODE                       0x8C7F
#define DWL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS           0x8C80
#define DWL_TRANSFORM_FEEDBACK_VARYINGS                          0x8C83
#define DWL_TRANSFORM_FEEDBACK_BUFFER_START                      0x8C84
#define DWL_TRANSFORM_FEEDBACK_BUFFER_SIZE                       0x8C85
#define DWL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN                0x8C88
#define DWL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS        0x8C8A
#define DWL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS              0x8C8B
#define DWL_INTERLEAVED_ATTRIBS                                  0x8C8C
#define DWL_SEPARATE_ATTRIBS                                     0x8C8D
#define DWL_TRANSFORM_FEEDBACK_BUFFER                            0x8C8E
#define DWL_TRANSFORM_FEEDBACK_BUFFER_BINDING                    0x8C8F
#define DWL_TRANSFORM_FEEDBACK                                   0x8E22
#define DWL_TRANSFORM_FEEDBACK_PAUSED                            0x8E23
#define DWL_TRANSFORM_FEEDBACK_ACTIVE                            0x8E24
#define DWL_TRANSFORM_FEEDBACK_BINDING                           0x8E25
#define DWL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING                0x8210
#define DWL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE                0x8211
#define DWL_FRAMEBUFFER_ATTACHMENT_RED_SIZE                      0x8212
#define DWL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE                    0x8213
#define DWL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE                     0x8214
#define DWL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE                    0x8215
#define DWL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE                    0x8216
#define DWL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE                  0x8217
#define DWL_FRAMEBUFFER_DEFAULT                                  0x8218
#define DWL_DEPTH24_STENCIL8                                     0x88F0
#define DWL_DRAW_FRAMEBUFFER_BINDING                             0x8CA6
#define DWL_READ_FRAMEBUFFER                                     0x8CA8
#define DWL_DRAW_FRAMEBUFFER                                     0x8CA9
#define DWL_READ_FRAMEBUFFER_BINDING                             0x8CAA
#define DWL_RENDERBUFFER_SAMPLES                                 0x8CAB
#define DWL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER                 0x8CD4
#define DWL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE                   0x8D56
#define DWL_UNIFORM_BUFFER                                       0x8A11
#define DWL_UNIFORM_BUFFER_BINDING                               0x8A28
#define DWL_UNIFORM_BUFFER_START                                 0x8A29
#define DWL_UNIFORM_BUFFER_SIZE                                  0x8A2A
#define DWL_MAX_VERTEX_UNIFORM_BLOCKS                            0x8A2B
#define DWL_MAX_FRAGMENT_UNIFORM_BLOCKS                          0x8A2D
#define DWL_MAX_COMBINED_UNIFORM_BLOCKS                          0x8A2E
#define DWL_MAX_UNIFORM_BUFFER_BINDINGS                          0x8A2F
#define DWL_MAX_UNIFORM_BLOCK_SIZE                               0x8A30
#define DWL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS               0x8A31
#define DWL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS             0x8A33
#define DWL_UNIFORM_BUFFER_OFFSET_ALIGNMENT                      0x8A34
#define DWL_ACTIVE_UNIFORM_BLOCKS                                0x8A36
#define DWL_UNIFORM_TYPE                                         0x8A37
#define DWL_UNIFORM_SIZE                                         0x8A38
#define DWL_UNIFORM_BLOCK_INDEX                                  0x8A3A
#define DWL_UNIFORM_OFFSET                                       0x8A3B
#define DWL_UNIFORM_ARRAY_STRIDE                                 0x8A3C
#define DWL_UNIFORM_MATRIX_STRIDE                                0x8A3D
#define DWL_UNIFORM_IS_ROW_MAJOR                                 0x8A3E
#define DWL_UNIFORM_BLOCK_BINDING                                0x8A3F
#define DWL_UNIFORM_BLOCK_DATA_SIZE                              0x8A40
#define DWL_UNIFORM_BLOCK_ACTIVE_UNIFORMS                        0x8A42
#define DWL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES                 0x8A43
#define DWL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER            0x8A44
#define DWL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER          0x8A46
#define DWL_OBJECT_TYPE                                          0x9112
#define DWL_SYNC_CONDITION                                       0x9113
#define DWL_SYNC_STATUS                                          0x9114
#define DWL_SYNC_FLAGS                                           0x9115
#define DWL_SYNC_FENCE                                           0x9116
#define DWL_SYNC_GPU_COMMANDS_COMPLETE                           0x9117
#define DWL_UNSIGNALED                                           0x9118
#define DWL_SIGNALED                                             0x9119
#define DWL_ALREADY_SIGNALED                                     0x911A
#define DWL_TIMEOUT_EXPIRED                                      0x911B
#define DWL_CONDITION_SATISFIED                                  0x911C
#define DWL_WAIT_FAILED                                          0x911D
#define DWL_SYNC_FLUSH_COMMANDS_BIT                              0x0001
#define DWL_COLOR                                                0x1800
#define DWL_DEPTH                                                0x1801
#define DWL_STENCIL                                              0x1802
#define DWL_MIN                                                  0x8007
#define DWL_MAX                                                  0x8008
#define DWL_DEPTH_COMPONENT24                                    0x81A6
#define DWL_STREAM_READ                                          0x88E1
#define DWL_STREAM_COPY                                          0x88E2
#define DWL_STATIC_READ                                          0x88E5
#define DWL_STATIC_COPY                                          0x88E6
#define DWL_DYNAMIC_READ                                         0x88E9
#define DWL_DYNAMIC_COPY                                         0x88EA
#define DWL_DEPTH_COMPONENT32F                                   0x8CAC
#define DWL_DEPTH32F_STENCIL8                                    0x8CAD
#define DWL_INVALID_INDEX                                        0xFFFF
#define DWL_TIMEOUT_IGNORED                                      -1
#define DWL_MAX_CLIENT_WAIT_TIMEOUT_WEBGL                        0x9247
#define DWL_VERTEX_ATTRIB_ARRAY_DIVISOR_ANGLE                    0x88FE
#define DWL_UNMASKED_VENDOR_WEBGL                                0x9245
#define DWL_UNMASKED_RENDERER_WEBGL                              0x9246
#define DWL_MAX_TEXTURE_MAX_ANISOTROPY_EXT                       0x84FF
#define DWL_TEXTURE_MAX_ANISOTROPY_EXT                           0x84FE
#define DWL_COMPRESSED_RGB_S3TC_DXT1_EXT                         0x83F0
#define DWL_COMPRESSED_RGBA_S3TC_DXT1_EXT                        0x83F1
#define DWL_COMPRESSED_RGBA_S3TC_DXT3_EXT                        0x83F2
#define DWL_COMPRESSED_RGBA_S3TC_DXT5_EXT                        0x83F3
#define DWL_COMPRESSED_R11_EAC                                   0x9270
#define DWL_COMPRESSED_SIGNED_R11_EAC                            0x9271
#define DWL_COMPRESSED_RG11_EAC                                  0x9272
#define DWL_COMPRESSED_SIGNED_RG11_EAC                           0x9273
#define DWL_COMPRESSED_RGB8_ETC2                                 0x9274
#define DWL_COMPRESSED_RGBA8_ETC2_EAC                            0x9275
#define DWL_COMPRESSED_SRGB8_ETC2                                0x9276
#define DWL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC                     0x9277
#define DWL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2             0x9278
#define DWL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2            0x9279
#define DWL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG                      0x8C00
#define DWL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG                     0x8C02
#define DWL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG                      0x8C01
#define DWL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG                     0x8C03
#define DWL_COMPRESSED_RGB_ETC1_WEBGL                            0x8D64
#define DWL_COMPRESSED_RGB_ATC_WEBGL                             0x8C92
#define DWL_COMPRESSED_RGBA_ATC_EXPLICIT_ALPHA_WEBGL             0x8C92
#define DWL_COMPRESSED_RGBA_ATC_INTERPOLATED_ALPHA_WEBGL         0x87EE
#define DWL_UNSIGNED_INT_24_8_WEBGL                              0x84FA
#define DWL_HALF_FLOAT_OES                                       0x8D61
#define DWL_RGBA32F_EXT                                          0x8814
#define DWL_RGB32F_EXT                                           0x8815
#define DWL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT            0x8211
#define DWL_UNSIGNED_NORMALIZED_EXT                              0x8C17
#define DWL_MIN_EXT                                              0x8007
#define DWL_MAX_EXT                                              0x8008
#define DWL_SRGB_EXT                                             0x8C40
#define DWL_SRGB_ALPHA_EXT                                       0x8C42
#define DWL_SRGB8_ALPHA8_EXT                                     0x8C43
#define DWL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING_EXT            0x8210
#define DWL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES                  0x8B8B
#define DWL_COLOR_ATTACHMENT0_WEBGL                              0x8CE0
#define DWL_COLOR_ATTACHMENT1_WEBGL                              0x8CE1
#define DWL_COLOR_ATTACHMENT2_WEBGL                              0x8CE2
#define DWL_COLOR_ATTACHMENT3_WEBGL                              0x8CE3
#define DWL_COLOR_ATTACHMENT4_WEBGL                              0x8CE4
#define DWL_COLOR_ATTACHMENT5_WEBGL                              0x8CE5
#define DWL_COLOR_ATTACHMENT6_WEBGL                              0x8CE6
#define DWL_COLOR_ATTACHMENT7_WEBGL                              0x8CE7
#define DWL_COLOR_ATTACHMENT8_WEBGL                              0x8CE8
#define DWL_COLOR_ATTACHMENT9_WEBGL                              0x8CE9
#define DWL_COLOR_ATTACHMENT10_WEBGL                             0x8CEA
#define DWL_COLOR_ATTACHMENT11_WEBGL                             0x8CEB
#define DWL_COLOR_ATTACHMENT12_WEBGL                             0x8CEC
#define DWL_COLOR_ATTACHMENT13_WEBGL                             0x8CED
#define DWL_COLOR_ATTACHMENT14_WEBGL                             0x8CEE
#define DWL_COLOR_ATTACHMENT15_WEBGL                             0x8CEF
#define DWL_DRAW_BUFFER0_WEBGL                                   0x8825
#define DWL_DRAW_BUFFER1_WEBGL                                   0x8826
#define DWL_DRAW_BUFFER2_WEBGL                                   0x8827
#define DWL_DRAW_BUFFER3_WEBGL                                   0x8828
#define DWL_DRAW_BUFFER4_WEBGL                                   0x8829
#define DWL_DRAW_BUFFER5_WEBGL                                   0x882A
#define DWL_DRAW_BUFFER6_WEBGL                                   0x882B
#define DWL_DRAW_BUFFER7_WEBGL                                   0x882C
#define DWL_DRAW_BUFFER8_WEBGL                                   0x882D
#define DWL_DRAW_BUFFER9_WEBGL                                   0x882E
#define DWL_DRAW_BUFFER10_WEBGL                                  0x882F
#define DWL_DRAW_BUFFER11_WEBGL                                  0x8830
#define DWL_DRAW_BUFFER12_WEBGL                                  0x8831
#define DWL_DRAW_BUFFER13_WEBGL                                  0x8832
#define DWL_DRAW_BUFFER14_WEBGL                                  0x8833
#define DWL_DRAW_BUFFER15_WEBGL                                  0x8834
#define DWL_MAX_COLOR_ATTACHMENTS_WEBGL                          0x8CDF
#define DWL_MAX_DRAW_BUFFERS_WEBGL                               0x8824
#define DWL_VERTEX_ARRAY_BINDING_OES                             0x85B5
#define DWL_QUERY_COUNTER_BITS_EXT                               0x8864
#define DWL_CURRENT_QUERY_EXT                                    0x8865
#define DWL_QUERY_RESULT_EXT                                     0x8866
#define DWL_QUERY_RESULT_AVAILABLE_EXT                           0x8867
#define DWL_TIME_ELAPSED_EXT                                     0x88BF
#define DWL_TIMESTAMP_EXT                                        0x8E28
#define DWL_GPU_DISJOINT_EXT                                     0x8FBB